export enum ErrorCodes {
  // Better-Auth error codes references.

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  FAILED_TO_CREATE_USER = 'FAILED_TO_CREATE_USER',
  FAILED_TO_CREATE_SESSION = 'FAILED_TO_CREATE_SESSION',
  FAILED_TO_UPDATE_USER = 'FAILED_TO_UPDATE_USER',
  FAILED_TO_GET_SESSION = 'FAILED_TO_GET_SESSION',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD',
  SOCIAL_ACCOUNT_ALREADY_LINKED = 'SOCIAL_ACCOUNT_ALREADY_LINKED',
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  ID_TOKEN_NOT_SUPPORTED = 'ID_TOKEN_NOT_SUPPORTED',
  FAILED_TO_GET_USER_INFO = 'FAILED_TO_GET_USER_INFO',
  USER_EMAIL_NOT_FOUND = 'USER_EMAIL_NOT_FOUND',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  EMAIL_CAN_NOT_BE_UPDATED = 'EMAIL_CAN_NOT_BE_UPDATED',
  CREDENTIAL_ACCOUNT_NOT_FOUND = 'CREDENTIAL_ACCOUNT_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  FAILED_TO_UNLINK_LAST_ACCOUNT = 'FAILED_TO_UNLINK_LAST_ACCOUNT',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  USER_ALREADY_HAS_PASSWORD = 'USER_ALREADY_HAS_PASSWORD',

  // Custom code from here

  USER_WITH_THIS_EMAIL_ALREADY_EXITS = 'USER_WITH_THIS_EMAIL_ALREADY_EXITS',
  UNEXPECTED_SERVER_ERROR = 'UNEXPECTED_SERVER_ERROR',
}

export type ErrorCodesTyped = `${ErrorCodes}`;

export interface BetterAuthErrorBody {
  code: ErrorCodes | ErrorCodesTyped;
  message: string;
}

export interface BetterAuthError {
  status: string;
  body: BetterAuthErrorBody;
  headers: Record<string, string>;
  statusCode: number;
}
